import Head from 'next/head';
import Hero from '@/components/hero/Hero';
import HomeDescription from '@/components/homeDescription/HomeDescription';
import SliderCard from "@/components/slider/SliderCard";

export default function Home() {
  return (
    <>
      <Head>
        <title>Track Travel</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <section id="solutions">
          <Hero />
          <HomeDescription />
          <SliderCard />
        </section>
      </div>
    </>
  )
}
